#!/bin/env bash

# apt stuff
alias p="sudo apt update && sudo apt install"
alias pu="sudo apt update"
alias puu="sudo apt update && sudo apt upgrade"
alias pr="sudo apt remove"

alias f="vifmrun"
alias n="nvim"
alias lg="lazygit"
alias ld="lazydocker"
