#!/bin/env bash

alias d="docker"
alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dcb="docker compose build"
alias dcrm="docker compose rm"
alias dci="docker compose images"
