#!/bin/env bash

alias g="git"
alias ga="git add"
alias gl="git log --oneline"
alias gla="git log"
alias gst="git status"
alias gp="git pull"
alias gP="git push"
alias gc="git commit -m"
alias gch="git checkout"
alias gb="git branch"
alias gd="git diff"
