#!/bin/env bash

alias k="kubectl"
alias ka="kubectl get all"

alias kp="kubectl get pods"
alias kr="kubectl get rs"
alias kd="kubectl get deployments"
alias ks="kubectl get services"

alias kc="kubectl create -f"

alias kdp="kubectl delete pod"
alias kdr="kubectl delete rs"
alias kdd="kubectl delete deployment"
alias kds="kubectl delete service"

alias kdsp="kubectl describe pod"
alias kdsr="kubectl describe rs"
alias kdsd="kubectl describe deployment"
alias kdss="kubectl describe service"
