#!/bin/env bash


if command -v pacman &> /dev/null
then
  alias p="sudo pacman -S --needed"
  alias pu="sudo pacman -Sy"
  alias puu="sudo pacman -Syu"
  alias pr="sudo pacman -Rv"
  alias pl="pacman -Ql"
  alias ps="pacman -Ss"
fi
