#!/bin/env bash

set -euo pipefail

run() {
	for app in "$@"; do
		if command -v "$app" &>/dev/null; then
			"$app"
			return 0
		fi
	done

	echo "No supported application found."
	return 1
}

run st gnome-terminal alacritty &

run pavucontrol &

run com.github.Eloston.UngoogledChromium &

run org.kde.dolphin &

# prevent screen from turning off
xset s off -dpms
