#!/bin/env bash

cd
wal -R
alacritty || st &
chromium &
transmission-qt || transmission-gtk &
nautilus || dolphin || thunar &
pavucontrol &
easyeffects &
/usr/lib/kdeconnectd &

xsetroot -name "  $(whoami)  "

# prevent screen from turning off
xset s off -dpms
