#!/bin/env bash

alias f="vifmrun"
alias n="nvim"
alias p="sudo pacman -Sy && sudo pacman -S"
alias pl="pacman -Ql"
alias lg="lazygit"
alias ld="lazydocker"

# pacman stuff
alias p="sudo pacman -S --needed"
alias pu="sudo pacman -Sy"
alias puu="sudo pacman -Syu"
alias pr="sudo pacman -Ru"
alias pl="pacman -Ql"

# Other
alias yt="yt-dlp"
