import = ["~/.config/alacritty/keys.yml"]

[window]
decorations = "none"
opacity = 0.85

[window.padding]
x = 15
y = 0

[font]
size = 14
builtin_box_drawing = true

[font.normal]
family = "CaskaydiaCove NFM"

[colors]
# name = "Ashes (dark)"
# author = "Chris Kempson"

[colors.primary]
background = "#1c2023"
foreground = "#c7ccd1"

[colors.cursor]
text = "#1c2023"
cursor = "#c7ccd1"

[colors.normal]
black = "#1c2023"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#c7ccd1"

[colors.bright]
black = "#747c84"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#f3f4f5"
